import { CODE_REVIEW_DETECTORS } from "./detectors-code-review.js";

/** Enterprise-level detectors — includes all code-review plus enterprise-specific checks. */
export const ENTERPRISE_DETECTORS: string[] = [
  // All code-review level detectors
  ...CODE_REVIEW_DETECTORS,
  // Enterprise: Product Strategy & Requirements (ENT-*)
  "detectVisionAlignment",
  "detectRoadmapConsistency",
  "detectKPICoverage",
  "detectOrphanRequirements",
  "detectRequirementTraceability",
  "detectAmbiguityPatterns",
  // Enterprise: Data Architecture & Persistence (ENT-DATA-*)
  "detectSchemaConsistency",
  "detectDataOwnership",
  "detectMissingMigrations",
  "detectIndexCoverage",
  // Enterprise: Reliability, Resilience & Concurrency (ENT-REL-*)
  "detectCircuitBreaker",
  "detectRetryPolicy",
  "detectTimeoutConfig",
  "detectHealthChecks",
  "detectGracefulDegradation",
  "detectRaceConditions",
  "detectDeadlockRisk",
  // Enterprise: Performance & Scalability (ENT-PERF-*)
  "detectNPlusOne",
  "detectMissingCaching",
  "detectStatefulServices",
  "detectMissingRateLimiting",
  "detectMissingTimeouts",
  // Enterprise: Observability (ENT-OBS-*)
  "detectMissingTracing",
  "detectLogStructure",
  "detectAlertCoverage",
  "detectMetricEndpoints",
  "detectMissingDashboard",
  "detectLogRetention",
  "detectDistributedLogging",
  "detectSLODefinitions",
  // Enterprise: Operations (ENT-OPS-*)
  "detectPipelineGaps",
  "detectRollbackCapability",
  "detectMissingRunbooks",
  "detectMonitoringGaps",
  "detectIncidentResponse",
  "detectDisasterRecovery",
  "detectCapacityPlanning",
  "detectChangeManagement",
  // Enterprise: Compliance (ENT-COMP-*)
  "detectOWASPTop10",
  "detectCWEMapping",
  "detectSOC2Controls",
  "detectNISTAlignment",
  "detectLGPDCompliance",
  "detectDataRetention",
  "detectConsentTracking",
  "detectSecretsInConfig",
  "detectEncryptionAtRest",
  "detectAccessControls",
  "detectAuditLogging",
  "detectComplianceReport",
  // Enterprise: Security Advanced (ENT-SEC-*)
  "detectSBOMCoverage",
  "detectDependencyProvenance",
  "detectTyposquatting",
  "detectLicenseConflicts",
  "detectTransitiveVulns",
  "detectMalwarePatterns",
  "detectDependencyStaleness",
  // Enterprise: Tech Debt (ENT-DEBT-*)
  "detectTechDebtCost",
  "detectTDR",
  "detectRemediationEffort",
  "detectDebtTrend",
  "detectHotspotFiles",
  "detectDebtByDomain",
  "detectROIRefactoring",
  "detectDebtAccumulationRate",
  // Enterprise: Supply Chain (ENT-SC-*)
  "detectSBOMExists",
  "detectSBOMCompleteness",
  "detectOutdatedDeps",
  "detectUnusedDeps",
  "detectLockFileSync",
  "detectDuplicateDeps",
  "detectDepAuditStatus",
];
