import { QUICK_DETECTORS } from "./detectors-quick.js";

/** Standard-level detectors — includes all quick-level plus structural and security checks. */
export const STANDARD_DETECTORS: string[] = [
  // Quick-level detectors
  ...QUICK_DETECTORS,
  // Structural detectors
  "detectBrokenRefs",
  "detectBrokenDirRefs",
  "detectNonBacktickFileRefs",
  "detectEmptyDirs",
  "detectOrphanDirs",
  "detectBareWordRefs",
  "detectExtensionMismatch",
  "detectReportNaming",
  "detectTemplateDirRefs",
  "detectAdrCoverage",
  "detectUnreferencedDirs",
  "detectP0Inconsistency",
  "detectViolationHotspots",
  "detectOrphanModules",
  "detectComplexityHotspots",
  "detectTestCoverageGaps",
  "detectConsoleUsage",
  "detectEmptyCatchBlocks",
  "detectHighComplexity",
  "detectUnusedExports",
  "detectDeadCodePatterns",
  // Security detectors — promoted from code-review to standard (OWASP coverage)
  "detectHardcodedSecrets",
  "detectSQLInjection",
  "detectXSS",
  "detectUnsafeEval",
  "detectConsoleSecrets",
  "detectWeakCrypto",
  "detectInsecureHTTP",
  "detectPrototypePollution",
  "detectPathTraversal",
  "detectRegexDos",
  "detectUnsafeDeserialization",
  "detectDependencyConfusion",
  "detectTaintFlow",
  "detectConfigSecrets",
  "detectInsecureCORS",
  "detectInsecureCookies",
  "detectWeakRandomness",
  "detectAccessibilityGaps",
  "detectOrphanSkillFiles",
  "detectBrokenSkillManifestEntries",
  "detectBrokenManifestRefs",
];
