import { STANDARD_DETECTORS } from "./detectors-standard.js";

/** Code-review-level detectors — includes all standard-plus plus governance, git, code quality, and architecture checks. */
export const CODE_REVIEW_DETECTORS: string[] = [
  // Standard-level detectors
  ...STANDARD_DETECTORS,
  // Code-review governance & consistency checks (standard + these = the original code-review set)
  "detectDeadRules",
  "detectSystemMapMismatch",
  "detectBrokenCommands",
  "detectTripleMaturityScore",
  "detectEmptyStack",
  "detectScriptWiring",
  "detectAgentContractRefs",
  "detectBufferSchemaMismatch",
  "detectRuleTypo",
  "detectNumberingGap",
  "detectDocCountMismatch",
  "detectCrossDocP0Contradiction",
  "detectEmptyDataFiles",
  "detectPhantomRuleRefs",
  "detectOrphanSkills",
  "detectCircularDeps",
  "detectTestHealth",
  "detectLintIssues",
  "detectTypeSafetyIssues",
  "detectUnpinnedVersions",
  "detectMissingLockFile",
  "detectLockFileDrift",
  "detectPhantomDependencies",
  "detectDeprecatedPackages",
  "detectDependencyVulnerabilities",
  "detectIncompatibleLicenses",
  // Git Intelligence (GIT-*)
  "detectCommitFormat",
  "detectBranchNaming",
  "detectDirectMainCommits",
  "detectForcePushes",
  "detectOrphanBranches",
  "detectCommitLanguage",
  "detectSecretsInGitHistory",
  "detectCommitWithoutGating",
  // Governance Enforcement (GOV-*)
  "detectIncompleteSessionClose",
  "detectMissingFeedback",
  "detectInvalidBacklogStates",
  "detectPlanFormat",
  "detectRuleExecutionCompliance",
  "detectPolicyStructure",
  "detectMissingPremortem",
  "detectMissingAdrForChanges",
  "detectDonePlanIntegrity",
  "detectMisclassifiedTier",
  // Code Quality Intelligence (CQ-*)
  "detectJSDocCoverage",
  "detectUnsafeTypeAssertions",
  "detectUnreachableCode",
  "detectUnusedImports",
  "detectMagicNumbers",
  "detectLongParams",
  "detectDeepNesting",
  "detectDuplicateCode",
  "detectGodFunctions",
  "detectCoverageThreshold",
  // Architecture Validation (ARCH-*)
  "detectCleanArchitectureLayers",
  "detectSRPViolations",
  "detectDependencyInversion",
  "detectBarrelFileCycles",
  "detectModuleCoupling",
  "detectImportConsistency",
  "detectTestStructure",
  "detectStaleVerification",
];
