/**
 * Detector map — Governance detectors builder
 */

import type { HealthIssue } from "../types.js";
import type { DetectorContext } from "./context.js";

import {
  detectDeadRules,
  detectViolationHotspots,
  detectMissingDocs,
  detectOrphanDirs,
  detectStaleBuffer,
  detectDatePlaceholders,
  detectEmptyDirs,
  detectBrokenRefs,
  detectBrokenDirRefs,
  detectNonBacktickFileRefs,
  detectMissingGitignore,
  detectMissingPackageJson,
  detectMaturityInconsistency,
  detectAdrCoverage,
  detectUnreferencedDirs,
  detectReportNaming,
  detectBareWordRefs,
  detectTemplateDirRefs,
  detectExtensionMismatch,
  detectSystemMapMismatch,
  detectBrokenCommands,
  detectP0Inconsistency,
  detectTripleMaturityScore,
  detectEmptyStack,
  detectScriptWiring,
  detectAgentContractRefs,
  detectBufferSchemaMismatch,
  detectRuleTypo,
  detectNumberingGap,
  detectDocCountMismatch,
  detectCrossDocP0Contradiction,
  detectEmptyDataFiles,
  detectPhantomRuleRefs,
  detectOrphanSkills,
  detectOrphanSkillFiles,
  detectBrokenSkillManifestEntries,
} from "../governance-detectors.js";

export function buildGovernanceDetectors(ctx: DetectorContext): Record<string, () => HealthIssue[]> {
  return {
    detectDeadRules: () => detectDeadRules(ctx.rules, ctx.history),
    detectViolationHotspots: () => detectViolationHotspots(ctx.history),
    detectMissingDocs: () => detectMissingDocs(ctx.shitennoDir),
    detectOrphanDirs: () => detectOrphanDirs(ctx.shitennoDir),
    detectStaleBuffer: () => detectStaleBuffer(ctx.shitennoDir),
    detectDatePlaceholders: () => detectDatePlaceholders(ctx.shitennoDir),
    detectEmptyDirs: () => detectEmptyDirs(ctx.shitennoDir),
    detectBrokenRefs: () => detectBrokenRefs(ctx.shitennoDir),
    detectBrokenDirRefs: () => detectBrokenDirRefs(ctx.shitennoDir),
    detectNonBacktickFileRefs: () => detectNonBacktickFileRefs(ctx.shitennoDir),
    detectMissingGitignore: () => detectMissingGitignore(ctx.shitennoDir),
    detectMaturityInconsistency: () => detectMaturityInconsistency(ctx.shitennoDir),
    detectAdrCoverage: () => detectAdrCoverage(ctx.shitennoDir),
    detectMissingPackageJson: () => detectMissingPackageJson(ctx.shitennoDir),
    detectUnreferencedDirs: () => detectUnreferencedDirs(ctx.shitennoDir),
    detectReportNaming: () => detectReportNaming(ctx.shitennoDir),
    detectBareWordRefs: () => detectBareWordRefs(ctx.shitennoDir),
    detectTemplateDirRefs: () => detectTemplateDirRefs(ctx.shitennoDir),
    detectExtensionMismatch: () => detectExtensionMismatch(ctx.shitennoDir),
    detectSystemMapMismatch: () => detectSystemMapMismatch(ctx.shitennoDir),
    detectBrokenCommands: () => detectBrokenCommands(ctx.shitennoDir),
    detectP0Inconsistency: () => detectP0Inconsistency(ctx.shitennoDir),
    detectTripleMaturityScore: () => detectTripleMaturityScore(ctx.shitennoDir),
    detectEmptyStack: () => detectEmptyStack(ctx.shitennoDir),
    detectScriptWiring: () => detectScriptWiring(ctx.projectRoot, ctx.shitennoDir),
    detectAgentContractRefs: () => detectAgentContractRefs(ctx.shitennoDir),
    detectBufferSchemaMismatch: () => detectBufferSchemaMismatch(ctx.shitennoDir),
    detectRuleTypo: () => detectRuleTypo(ctx.shitennoDir),
    detectNumberingGap: () => detectNumberingGap(ctx.shitennoDir),
    detectDocCountMismatch: () => detectDocCountMismatch(ctx.shitennoDir),
    detectCrossDocP0Contradiction: () => detectCrossDocP0Contradiction(ctx.shitennoDir),
    detectEmptyDataFiles: () => detectEmptyDataFiles(ctx.shitennoDir),
    detectPhantomRuleRefs: () => detectPhantomRuleRefs(ctx.shitennoDir),
    detectOrphanSkills: () => detectOrphanSkills(ctx.shitennoDir),
    detectOrphanSkillFiles: () => detectOrphanSkillFiles(ctx.shitennoDir),
    detectBrokenSkillManifestEntries: () => detectBrokenSkillManifestEntries(ctx.shitennoDir),
  };
}
