import type { ClassificationRule } from "../taxonomy.js";

export const PERSISTENCE_AUTH_SECURITY_RULES: ClassificationRule[] = [
  // ── Persistence ─────────────────────────────────────────────────────────
  {
    signal: "dependency.added",
    match: /\b(pg|mysql|sqlite|typeorm|prisma|drizzle|knex|sequelize|mongoose|mongodb)\b/i,
    domain: "persistence",
    subdomain: "database-driver",
    priority: 100,
    confidenceBoost: 0.9,
    description: "Database driver or ORM dependency added",
  },
  {
    signal: "file.created",
    match: /(?:migrations?\/|\.migration\.|migrate)/i,
    domain: "persistence",
    subdomain: "schema-migration",
    priority: 90,
    confidenceBoost: 0.85,
    description: "Migration file created",
  },
  {
    signal: "config.changed",
    match: /(?:DATABASE_URL|DB_HOST|DB_PORT|DB_NAME|CONNECTION_STRING|REDIS_URL)/i,
    domain: "persistence",
    subdomain: "connection-config",
    priority: 95,
    confidenceBoost: 0.9,
    description: "Database connection configuration changed",
  },
  {
    signal: "file.modified",
    match: /(?:src\/db\/|src\/repositories\/|src\/models\/|src\/entities\/)/i,
    domain: "persistence",
    subdomain: "data-access",
    priority: 80,
    confidenceBoost: 0.7,
    description: "Data access layer file modified",
  },
  {
    signal: "file.created",
    match: /(?:src\/db\/|src\/repositories\/|src\/models\/|src\/entities\/)/i,
    domain: "persistence",
    subdomain: "data-access",
    priority: 85,
    confidenceBoost: 0.75,
    description: "Data access layer file created",
  },

  // ── Authentication ──────────────────────────────────────────────────────
  {
    signal: "dependency.added",
    match: /\b(passport|jsonwebtoken|bcrypt|oauth|argon2|jose|iron-session)\b/i,
    domain: "authentication",
    subdomain: "auth-library",
    priority: 100,
    confidenceBoost: 0.9,
    description: "Authentication library dependency added",
  },
  {
    signal: "file.created",
    match: /(?:src\/auth\/|src\/middleware\/auth|.*\.auth\.(?:ts|js))/i,
    domain: "authentication",
    subdomain: "auth-middleware",
    priority: 90,
    confidenceBoost: 0.85,
    description: "Authentication middleware or module created",
  },
  {
    signal: "file.modified",
    match: /(?:src\/auth\/|src\/middleware\/auth|.*\.auth\.(?:ts|js))/i,
    domain: "authentication",
    subdomain: "auth-middleware",
    priority: 85,
    confidenceBoost: 0.8,
    description: "Authentication module modified",
  },

  // ── Security ────────────────────────────────────────────────────────────
  {
    signal: "dependency.added",
    match: /\b(helmet|cors|rate-limit|csrf|xss-clean|express-validator|zod)\b/i,
    domain: "security",
    subdomain: "security-library",
    priority: 100,
    confidenceBoost: 0.85,
    description: "Security library dependency added",
  },
  {
    signal: "config.changed",
    match: /(?:JWT_SECRET|API_KEY|SECRET|ENCRYPTION_KEY|SECURITY_TOKEN)/i,
    domain: "security",
    subdomain: "secret-config",
    priority: 100,
    confidenceBoost: 0.95,
    description: "Security secret or key configuration changed",
  },
  {
    signal: "file.created",
    match: /(?:src\/security\/|.*\.security\.(?:ts|js)|.*\.test\.security\.)/i,
    domain: "security",
    subdomain: "security-test",
    priority: 90,
    confidenceBoost: 0.8,
    description: "Security test or module created",
  },

  // ── Infrastructure ──────────────────────────────────────────────────────
  {
    signal: "dependency.added",
    match: /\b(docker|kubernetes|terraform|aws-sdk|@aws-sdk|@google-cloud|@azure)\b/i,
    domain: "infrastructure",
    subdomain: "infra-tool",
    priority: 100,
    confidenceBoost: 0.85,
    description: "Infrastructure tool dependency added",
  },
  {
    signal: "file.created",
    match: /(?:Dockerfile|docker-compose|\.github\/workflows\/|\.gitlab-ci|Jenkinsfile)/i,
    domain: "infrastructure",
    subdomain: "deploy-config",
    priority: 95,
    confidenceBoost: 0.9,
    description: "Deployment configuration file created",
  },
  {
    signal: "file.created",
    match: /(?:\.github\/|\.gitlab-ci|vercel\.json|netlify\.toml|fly\.toml)/i,
    domain: "infrastructure",
    subdomain: "ci-cd",
    priority: 90,
    confidenceBoost: 0.85,
    description: "CI/CD configuration file created",
  },
];
