/**
 * mandatory-context-generator.ts — Generates MANDATORY_CONTEXT.md
 *
 * Concatenates every skill and rule that is `mandatory` with no `when` condition
 * (i.e., applies to literally every session) into a single file that opencode
 * can inject via `instructions`. Task-scoped mandatory skills can't be
 * pre-resolved since opencode has no equivalent of a live getSkills(taskMeta) call.
 *
 * PRINCIPLE: MCP-based agents get precise scope-resolved skills at call time.
 * opencode-native agents get the always-applicable subset auto-injected at session
 * start, generated from the exact same manifest — so the two paths can't drift.
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { parse as parseYaml } from "yaml";
import { type ManifestEntry } from "./manifest-resolver.js";

/**
 * Read a YAML manifest file and return its entries under the given key.
 */
function readManifest(
  manifestPath: string,
  key: string
): ManifestEntry[] {
  if (!existsSync(manifestPath)) return [];
  const raw = readFileSync(manifestPath, "utf-8");
  const parsed = parseYaml(raw) as Record<string, ManifestEntry[]>;
  return parsed[key] ?? [];
}

/**
 * Read the raw content of a file, returning null if not found.
 */
function readContent(filePath: string): string | null {
  if (!existsSync(filePath)) return null;
  return readFileSync(filePath, "utf-8");
}

function renderEntries(
  shitennoDir: string,
  entries: ManifestEntry[],
  heading: string
): string[] {
  if (entries.length === 0) return [];
  const lines = [heading, ""];
  for (const entry of entries) {
    const content = readContent(join(shitennoDir, entry.path));
    lines.push(`### ${entry.id}`, "");
    lines.push(content ? content.trim() : `> ⚠️ File not found: \`${entry.path}\``);
    lines.push("");
  }
  return lines;
}

/**
 * Generate MANDATORY_CONTEXT.md from the skill and rule manifests.
 *
 * Only entries that are `mandatory: true` AND have no `when` condition
 * (truly unconditional — apply to every session) are included.
 * Task-scoped mandatory entries (e.g. `mandatory: true` with `when: { task: implementation }`)
 * are excluded because they can't be pre-resolved at generation time.
 *
 * @param shitennoDir - Path to the .shitenno directory (or shitenno/)
 * @param outputPath - Path where MANDATORY_CONTEXT.md will be written
 * @returns true if the file was written, false if nothing changed or error
 */
export function generateMandatoryContext(
  shitennoDir: string,
  outputPath: string
): boolean {
  const ruleManifestPath = join(shitennoDir, "governance", "rule-manifest.yaml");
  const skillManifestPath = join(shitennoDir, "governance", "skill-manifest.yaml");

  const rules = readManifest(ruleManifestPath, "rules");
  const skills = readManifest(skillManifestPath, "skills");

  const unconditionalRules = rules.filter((r) => r.mandatory && !r.when);
  const unconditionalSkills = skills.filter((s) => s.mandatory && !s.when);

  if (unconditionalRules.length === 0 && unconditionalSkills.length === 0) {
    if (existsSync(outputPath)) {
      writeFileSync(outputPath, "<!-- No unconditional mandatory entries found -->\n", "utf-8");
    }
    return false;
  }

  const sections: string[] = [
    "# MANDATORY CONTEXT — Always-Applicable Rules & Skills",
    "",
    "> **Generated file.** Do not edit manually. Re-generated by `shugo sync`.",
    "> This file concatenates every rule and skill that is mandatory with no `when`",
    "> condition — i.e., applies to literally every session.",
    "> Task-scoped mandatory entries are resolved at runtime via MCP `getSkills`.",
    "",
    ...renderEntries(shitennoDir, unconditionalRules, "## Mandatory Rules (always active)"),
    ...renderEntries(shitennoDir, unconditionalSkills, "## Mandatory Skills (always active)"),
  ];

  writeFileSync(outputPath, sections.join("\n"), "utf-8");
  return true;
}
